#### **ndarray中，欄：axis=0; 列：axis=1**

In [ ]:
import pandas as pd
df = pd.read_csv('taiwan.csv')
display(df)

#### **局部區域 索引 df.iloc[列, 欄] ｜ 名稱 df.loc[列, 欄]**

##### **遮色片功能(篩選應用)**

In [ ]:
df.iloc[:5]
df.loc[[0,1,2,3,4]]
df1 = df.iloc[705:715]
df1['新增確診數']>=12

705    False
706     True
707     True
708     True
709     True
710     True
711     True
712     True
713     True
714     True
Name: 新增確診數, dtype: bool

In [11]:
df.iloc[:5]
df.loc[[0,1,2,3,4]]
df1 = df.iloc[705:715]
mask = df1['新增確診數']>=12
df1[mask]

     國家          日期   總確診數  新增確診數  新增死亡數
706  台灣  2021-12-22  16840     14      0
707  台灣  2021-12-23  16853     13      0
708  台灣  2021-12-24  16873     20      0
709  台灣  2021-12-25  16891     18      0
710  台灣  2021-12-26  16915     24      0
711  台灣  2021-12-27  16931     16      0
712  台灣  2021-12-28  16950     19      0
713  台灣  2021-12-29  16964     14      0
714  台灣  2021-12-30  16988     24      0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 903 entries, 0 to 902
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國家      903 non-null    object
 1   日期      903 non-null    object
 2   總確診數    903 non-null    int64
 3   新增確診數   903 non-null    int64
 4   新增死亡數   903 non-null    int64
dtypes: int64(3), object(2)
memory usage: 35.4+ KB

In [4]:
df[["日期", "總確診數"]]

             日期     總確診數
0    2020-01-16        0
1    2020-01-17        0
2    2020-01-18        0
3    2020-01-19        0
4    2020-01-20        0
..          ...      ...
898  2022-07-02  3837856
899  2022-07-03  3870528
900  2022-07-04  3893643
901  2022-07-05  3929627
902  2022-07-06  3964188

[903 rows x 2 columns]

##### **遮色片應用**

In [13]:
df
df['日期'] <= '2020-01-20'

0       True
1       True
2       True
3       True
4       True
       ...
898    False
899    False
900    False
901    False
902    False
Name: 日期, Length: 903, dtype: bool

##### **抓取特定日期區間的資料**

In [14]:
mask=(df['日期'] >= '2020-01-20')&(df['日期'] <= '2020-02-01')
df[mask]

    國家          日期  總確診數  新增確診數  新增死亡數
4   台灣  2020-01-20     0      0      0
5   台灣  2020-01-21     0      0      0
6   台灣  2020-01-22     1      0      0
7   台灣  2020-01-23     1      0      0
8   台灣  2020-01-24     3      2      0
9   台灣  2020-01-25     3      0      0
10  台灣  2020-01-26     4      1      0
11  台灣  2020-01-27     5      1      0
12  台灣  2020-01-28     8      3      0
13  台灣  2020-01-29     8      0      0
14  台灣  2020-01-30     9      1      0
15  台灣  2020-01-31    10      1      0
16  台灣  2020-02-01    10      0      0